FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

ENV NODE_ENV=production

COPY index.html ./
COPY vite.config.js ./
COPY src/ src/
COPY public/ public/

RUN npm run build

COPY serve.json dist/

EXPOSE 5000

CMD ["npx", "serve", "-s", "dist", "-l", "5000", "--config", "serve.json"]
