# Stage 1: Base
FROM node:18-alpine AS base
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Stage 3: Production
FROM base AS production
RUN npm run build
EXPOSE 5000
CMD ["npx", "serve", "-s", "dist", "-l", "5000"]
