apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - version-configmap-dev.yaml
  - https://github.com/pipelinedave/k3s-config.git/kustomize/choremane/overlays/dev

replacements:
- source:
    fieldPath: data.VERSION_TAG
    kind: ConfigMap
    name: choremane-version
- source:
    fieldPath: data.BACKEND_IMAGE
    kind: ConfigMap
    name: choremane-version
- source:
    fieldPath: data.FRONTEND_IMAGE
    kind: ConfigMap
    name: choremane-version
