apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: choremane
build:
  hooks:
    before:
      - command:
        - sh
        - -c
        - |
          VERSION_TAG="choremane/dev/$(date +%s)"
          BACKEND_IMAGE="pipelinedave/choremane-backend:${VERSION_TAG}"
          FRONTEND_IMAGE="pipelinedave/choremane-frontend:${VERSION_TAG}"
          cat <<EOF > version-configmap.yaml
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: choremane-version
          data:
            VERSION_TAG: "${VERSION_TAG}"
            BACKEND_IMAGE: "${BACKEND_IMAGE}"
            FRONTEND_IMAGE: "${FRONTEND_IMAGE}"
          EOF
  artifacts:
    - image: docker.io/pipelinedave/choremane-frontend
      context: frontend/
      sync:
        infer:
          - 'src/**/*'
    - image: docker.io/pipelinedave/choremane-backend
      context: backend/
      sync:
        infer: ['**/*']
  local:
    push: true
  tagPolicy:
    envTemplate:
      template: 'dev'
manifests:
  kustomize:
    paths:
      - '.'
portForward:
  - resourceType: Service
    resourceName: backend-service
    namespace: choremane-dev
    port: 80
    localPort: 8090
  - resourceType: Service
    resourceName: frontend-service
    namespace: choremane-dev
    port: 80
    localPort: 8091
