apiVersion: v1
kind: ConfigMap
metadata:
  name: choremane-version
data:
  VERSION_TAG: "choremane/prod/v3"
  BACKEND_IMAGE: "pipelinedave/choremane-api:8a7ec047b74583c89c1aeb7a2c00c329165e750d"
  FRONTEND_IMAGE: "pipelinedave/choremane-frontend:8a7ec047b74583c89c1aeb7a2c00c329165e750d"
