apiVersion: v1
kind: ConfigMap
metadata:
  name: choremane-version
data:
  VERSION_TAG: "HEAD"
  BACKEND_IMAGE: "pipelinedave/choremane-api:c38fad2671328bf325ca89a6f3a27aaae4f3f424"
  FRONTEND_IMAGE: "pipelinedave/choremane-frontend:c38fad2671328bf325ca89a6f3a27aaae4f3f424"
