apiVersion: v1
kind: ConfigMap
metadata:
  name: choremane-version
data:
  VERSION_TAG: "HEAD"
  BACKEND_IMAGE: "pipelinedave/choremane-api:e9d6263c1a57f2e23c924069cd2acd15cdfaee72"
  FRONTEND_IMAGE: "pipelinedave/choremane-frontend:e9d6263c1a57f2e23c924069cd2acd15cdfaee72"
