  name: Deploy to Kubernetes

  description: Updates deployment files in the k3s-config repository and tags the deployment.

  inputs:
    environment:
      description: 'Deployment environment (staging or production)'
      required: true
    k3s_repo:
      description: 'The k3s-config repository name'
      required: true
    version_tag:
      description: 'The version tag for the deployment'
      required: true
    k3s_config_token:
      description: 'GitHub token for accessing the k3s-config repository'
      required: true

  runs:
    using: 'composite'
    steps:
      - name: 📥 Checkout k3s-config Repo
        uses: actions/checkout@v3
        with:
          repository: ${{ inputs.k3s_repo }}
          token: ${{ inputs.k3s_config_token }}
          ref: main
          fetch-depth: 0

      - name: 🔧 Ensure Up-to-date Main
        shell: bash
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git pull --rebase origin main

      - name: 📝 Create Version ConfigMap
        shell: bash
        run: |
          cat <<EOF > kustomize/choremane/overlays/${{ inputs.environment }}/version-configmap.yaml
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: choremane-version
          data:
            VERSION_TAG: ${{ inputs.version_tag }}
            BACKEND_IMAGE: "${{ env.BACKEND_IMAGE }}"
            FRONTEND_IMAGE: "${{ env.FRONTEND_IMAGE }}"
          EOF

      - name: 🔧 Update Deployment Manifests
        shell: bash
        run: |
          sed -i "s|image: pipelinedave/choremane-backend:.*|image: ${{ env.BACKEND_IMAGE }}|g" "kustomize/choremane/overlays/${{ inputs.environment }}/backend-deployment-patch.yaml" || echo "🔴 No backend-deployment-patch.yaml found."
          sed -i "s|image: pipelinedave/choremane-frontend:.*|image: ${{ env.FRONTEND_IMAGE }}|g" "kustomize/choremane/overlays/${{ inputs.environment }}/frontend-deployment-patch.yaml" || echo "🔴 No frontend-deployment-patch.yaml found."

      - name: 💾 Commit & Push Changes
        shell: bash
        run: |
          git remote set-url origin "https://x-access-token:${{ inputs.k3s_config_token }}@github.com/${{ inputs.k3s_repo }}.git"
          git add kustomize/choremane/overlays/${{ inputs.environment }}/version-configmap.yaml
          git add kustomize/choremane/overlays/${{ inputs.environment }}/backend-deployment-patch.yaml || true
          git add kustomize/choremane/overlays/${{ inputs.environment }}/frontend-deployment-patch.yaml || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update ConfigMap and ${inputs.environment} deployments for ${{ inputs.version_tag }} with BACKEND: ${{  env.BACKEND_IMAGE  }} and FRONTEND: ${{ env.FRONTEND_IMAGE }}"
            git push origin HEAD:main
          fi

      - name: 🏷️ Tag in k3s-config Repo
        shell: bash
        run: |
          git tag "choremane/${{ inputs.environment }}/${{ github.run_attempt }}"
          git push origin "${{ inputs.version_tag }}"
