name: Build Backend Docker Image
description: Builds the Docker image for the backend application.

runs:
  using: 'composite'
  steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: 🐍 Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: 📦 Install Dependencies
      shell: bash
      run: pip install -r backend/requirements.txt

    - name: 🔧 Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 🔑 Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 🏭 Build & Push Backend Image
      id: build_backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        file: ./backend/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: |
          ${{ github.repository_owner }}/choremane-backend:latest
          ${{ github.repository_owner }}/choremane-backend:${{ github.sha }}
