name: Push Docker Images
description: Pushes the built Docker images to the registry.

runs:
  using: 'composite'
  steps:
    - name: 🔧 Setup Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: 🔑 Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: 🏭 Push Backend Image
      shell: bash
      run: |
        docker push ${{ github.repository_owner }}/choremane-backend:latest
        docker push ${{ github.repository_owner }}/choremane-backend:${{ github.sha }}

    - name: 🏭 Push Frontend Image
      shell: bash
      run: |
        docker push ${{ github.repository_owner }}/choremane-frontend:latest
        docker push ${{ github.repository_owner }}/choremane-frontend:${{ github.sha }}
