name: 🏗️ Build, Push & Deploy ✨

on:
  push:
    tags:
      - 'choremane/**/v*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 📥 Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 🔧 Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: 🔑 Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🏭 Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            pipelinedave/choremane-api:latest
            pipelinedave/choremane-api:${{ github.sha }}

      - name: 🏭 Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            pipelinedave/choremane-frontend:latest
            pipelinedave/choremane-frontend:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/choremane/')
    permissions:
      contents: write
    steps:
      - name: 📥 Checkout k3s-config repo
        uses: actions/checkout@v3
        with:
          repository: pipelinedave/k3s-config
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: 🪄 Prepare Variables
        run: |
          VERSION_TAG="${GITHUB_REF#refs/tags/}"
          BACKEND_IMAGE="pipelinedave/choremane-api:${{ github.sha }}"
          FRONTEND_IMAGE="pipelinedave/choremane-frontend:${{ github.sha }}"
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV
          echo "BACKEND_IMAGE=$BACKEND_IMAGE" >> $GITHUB_ENV
          echo "FRONTEND_IMAGE=$FRONTEND_IMAGE" >> $GITHUB_ENV

      - name: 📝 Create Version ConfigMap
        run: |
          cat <<EOF > version-configmap.yaml
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: choremane-version
          data:
            VERSION_TAG: "${VERSION_TAG}"
            BACKEND_IMAGE: "${BACKEND_IMAGE}"
            FRONTEND_IMAGE: "${FRONTEND_IMAGE}"
          EOF

      - name: 🔧 Update Deployment Manifests
        run: |
          # Use sed or yq to update backend and frontend images in your manifests.
          # Adjust paths as needed for your actual manifests.
          sed -i "s|image: pipelinedave/choremane-api:.*|image: ${BACKEND_IMAGE}|g" ./deployments/backend-deployment.yaml || echo "🔴 [GUESS]: No backend-deployment.yaml found."
          sed -i "s|image: pipelinedave/choremane-frontend:.*|image: ${FRONTEND_IMAGE}|g" ./deployments/frontend-deployment.yaml || echo "🔴 [GUESS]: No frontend-deployment.yaml found."

      - name: 💾 Commit Changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add version-configmap.yaml
          git add deployments/
          git commit -m "Update ConfigMap and deployments for ${{ env.VERSION_TAG }} with images ${{ github.sha }}"
          git push

      - name: 🏷️ Tag in k3s-config Repo
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag "${VERSION_TAG}"
          git push origin "${VERSION_TAG}"
