name: Build and Tag Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            pipelinedave/choremane-api:latest
            pipelinedave/choremane-api:${{ github.sha }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            pipelinedave/choremane-frontend:latest
            pipelinedave/choremane-frontend:${{ github.sha }}

      - name: Prepare Version ConfigMap
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION_TAG="${GITHUB_REF#refs/tags/}"
          else
            VERSION_TAG="HEAD"
          fi
          BACKEND_IMAGE="pipelinedave/choremane-api:${{ github.sha }}"
          FRONTEND_IMAGE="pipelinedave/choremane-frontend:${{ github.sha }}"
          cat <<EOF > version-configmap.yaml
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: choremane-version
          data:
            VERSION_TAG: "${VERSION_TAG}"
            BACKEND_IMAGE: "${BACKEND_IMAGE}"
            FRONTEND_IMAGE: "${FRONTEND_IMAGE}"
          EOF

      - name: Commit ConfigMap
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add version-configmap.yaml
          git commit -m "Add version-configmap for ${{ github.sha }}"
          git push origin HEAD:main

  tag:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create and Push Tag
        env:
          TAG: v${{ github.run_number }}
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag $TAG
          git push origin $TAG

  release:
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            ## Changes
            - Automated release for commit ${{ github.sha }}
          draft: false
          prerelease: false
