name: Build and Tag Release

on:
  push:
    branches:
      - main
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend Image
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          file: ./backend/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            pipelinedave/choremane-api:latest
            pipelinedave/choremane-api:${{ github.sha }}

      - name: Build and Push Frontend Image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            pipelinedave/choremane-frontend:latest
            pipelinedave/choremane-frontend:${{ github.sha }}

      - name: Prepare Version ConfigMap
        run: |
          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            VERSION_TAG="${GITHUB_REF#refs/tags/}"
          else
            VERSION_TAG="HEAD"
          fi
          BACKEND_IMAGE="pipelinedave/choremane-api:${{ github.sha }}"
          FRONTEND_IMAGE="pipelinedave/choremane-frontend:${{ github.sha }}"
          cat <<EOF > version-configmap.yaml
          apiVersion: v1
          kind: ConfigMap
          metadata:
            name: choremane-version
          data:
            VERSION_TAG: "${VERSION_TAG}"
            BACKEND_IMAGE: "${BACKEND_IMAGE}"
            FRONTEND_IMAGE: "${FRONTEND_IMAGE}"
          EOF

      - name: Commit ConfigMap
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

          if [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
            git remote set-url origin "https://github.com/pipelinedave/k3s-config.git"
            git checkout -b "${TAG}"
            git add version-configmap.yaml
            git commit -m "Add version-configmap for ${{ github.sha }} at tag ${TAG}"
            git push origin "${TAG}"
          else
            git add version-configmap.yaml
            git commit -m "Add version-configmap for ${{ github.sha }}"
            git push origin HEAD:main
          fi

  tag:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    steps:
      - name: Checkout k3s-config repo
        uses: actions/checkout@v3
        with:
          repository: pipelinedave/k3s-config
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Recreate Tag in k3s-config
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          TAG="${GITHUB_REF#refs/tags/}"
          git tag "${TAG}"
          git push origin "${TAG}"


  # release:
  #   runs-on: ubuntu-latest
  #   needs: tag
  #   permissions:
  #     contents: write
  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v3

  #     - name: Create GitHub Release
  #       uses: actions/create-release@v1
  #       with:
  #         tag_name: v${{ github.run_number }}
  #         release_name: Release ${{ github.run_number }}
  #         body: |
  #           ## Changes
  #           - Automated release for commit ${{ github.sha }}
  #         draft: false
  #         prerelease: false
