name: ✨ Prod ✨

on:
  push:
    tags:
      - 'choremane/prod/v.*'
  workflow_dispatch:

jobs:
  build-and-push:
    uses: ./.github/workflows/build-and-push.yaml
    with:
      environment: 'prod'
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      K3S_CONFIG_TOKEN: ${{ secrets.K3S_CONFIG_TOKEN }}
