name: Deploy to Production
on:
  push:
    tags:
      - "*prod*"

jobs:
  tag-backend:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image_name: pipelinedave/choremane-backend
      image_tag: ${{ github.ref_name }}
      context: ./backend
      dockerfile: ./backend/Dockerfile
      skip_build: "true"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  tag-frontend:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image_name: pipelinedave/choremane-frontend
      image_tag: ${{ github.ref_name }}
      context: ./frontend
      dockerfile: ./frontend/Dockerfile.prod
      skip_build: "true"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: [tag-backend, tag-frontend]
    uses: ./.github/workflows/update-kubernetes-deployment.yml
    with:
      overlay: "production"
      version_tag: ${{ github.ref_name }}
      backend_image: pipelinedave/choremane-backend:${{ github.ref_name }}
      frontend_image: pipelinedave/choremane-frontend:${{ github.ref_name }}
    secrets:
      K3S_CONFIG_TOKEN: ${{ secrets.K3S_CONFIG_TOKEN }}
