name: Deploy to Staging
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-backend:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image_name: pipelinedave/choremane-backend
      image_tag: ${{ github.sha }}
      context: ./backend
      dockerfile: ./backend/Dockerfile
      skip_build: "false"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  build-frontend:
    uses: ./.github/workflows/build-and-push.yml
    with:
      image_name: pipelinedave/choremane-frontend
      image_tag: ${{ github.sha }}
      context: ./frontend
      dockerfile: ./frontend/Dockerfile.prod
      skip_build: "false"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: [build-backend, build-frontend]
    uses: ./.github/workflows/update-kubernetes-deployment.yml
    with:
      overlay: "staging"
      version_tag: ${{ github.sha }}
      backend_image: pipelinedave/choremane-backend:${{ github.sha }}
      frontend_image: pipelinedave/choremane-frontend:${{ github.sha }}
    secrets:
      K3S_CONFIG_TOKEN: ${{ secrets.K3S_CONFIG_TOKEN }}
